# Generated by Django 3.2.6 on 2021-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='adhar',
            field=models.BigIntegerField(default=None, unique=True),
        ),
    ]
