# Generated by Django 3.2 on 2021-05-11 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state_city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('Comp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Comp_Title', models.CharField(max_length=80)),
                ('Comp_Desc', models.TextField()),
                ('Address', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Action_Taken', models.CharField(max_length=90)),
                ('Progress', models.IntegerField()),
                ('Comp_Date', models.DateField()),
                ('City_Id', models.ForeignKey(db_column='City_Id', on_delete=django.db.models.deletion.CASCADE, to='state_city.cities')),
                ('Comp_By', models.ForeignKey(db_column='Comp_By', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('State_Id', models.ForeignKey(db_column='State_Id', on_delete=django.db.models.deletion.CASCADE, to='state_city.states')),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
    ]
