# Generated by Django 3.2 on 2021-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='Action_Taken',
            field=models.CharField(default='none', max_length=90),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='Progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='Status',
            field=models.CharField(default='not started', max_length=20),
        ),
    ]
