# Generated by Django 3.2 on 2021-05-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20210511_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='Action_Taken',
            new_name='action_taken',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='City_Id',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Comp_By',
            new_name='comp_by',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Comp_Date',
            new_name='comp_date',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Comp_Desc',
            new_name='comp_desc',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Comp_Id',
            new_name='comp_id',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Comp_Title',
            new_name='comp_title',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Progress',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='State_Id',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='Status',
            new_name='status',
        ),
    ]
