# Generated by Django 3.2 on 2021-05-11 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state_city', '0001_initial'),
        ('complaints', '0003_auto_20210511_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='state_city.cities'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='comp_by',
            field=models.ForeignKey(db_column='comp_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='state_id',
            field=models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='state_city.states'),
        ),
        migrations.AlterModelTable(
            name='complaints',
            table='complaints',
        ),
    ]
