# Generated by Django 3.2 on 2021-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20210511_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='comp_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='comp_video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='comp_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
